version: '3.7'

services:
  web:
    # php 8.0.14
    image: 8ct8pus/apache-php-alpine:1.0.7
    # php 7.4.12
    #image: 8ct8pus/apache-php-alpine:1.0.4
    # development image
    #image: apache-php-alpine:dev
    container_name: web
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=localhost
      - DOCUMENT_ROOT=/public
    volumes:
      # development directory
      - ./html/:/var/www/html/
      # expose apache logs to host
      - ./docker/log/:/var/log/apache2/
      # expose apache2 and php config to host
      - ./docker/etc/:/docker/etc/
      # expose ssl certificates to host
      - ./docker/ssl/:/etc/ssl/apache2/
